---
title: 'Synthetic Controls: Sike and Slab Edition'
author: "Donald R. Williams"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Packages
```{r}
library(BoomSpikeSlab)
library(tidyverse)
library(ggplot2)
library(haven)
library(dplyr)
```
## Data Prep

```{r}
read_data <- function(df){
  full_path <- paste("https://raw.github.com/scunning1975/mixtape/master/", 
                     df, sep = "")
  df <- read_dta(full_path)
  return(df)
}

texas <- read_data("texas.dta") %>%
  as.data.frame(.)

control_fips <- c(1,2,4:6,8:13,15:42,44:51,53:56)
adj_factor <- 10000
texas$bmpercap <- texas$bmprison / texas$bmpop
texas_bscm <- texas[texas$statefip %in% control_fips, 
                    c("year", "statefip", "bmprison")] %>%
  pivot_wider(names_from= statefip, values_from = bmprison,
              names_prefix = "statefips_")

X <- texas_bscm[,str_detect(colnames(texas_bscm), "statefips_48") == FALSE]
y <- texas_bscm[, "statefips_48"]
X_train <- X[X$year <= 1993, 2:51] / adj_factor
X_test <- X[X$year > 1993, 2:51] / adj_factor
y_train <- y[1:9, ] / adj_factor
y_test <- y[10:16, ] / adj_factor
```


## Helper function
```{r}
get_qs <- function(draws){
  
  tmp <- apply(draws, 2, function(x) quantile(x, c(0.025, .5, 0.975))) * adj_factor
  tmp <- t(tmp) 
  tmp <- data.frame(tmp)
  tmp$true <- rep(NA, nrow(tmp))
  tmp$true <- c(y_train$statefips_48, y_test$statefips_48) * adj_factor
  tmp$years <- c(1985:2000)
  return(tmp)
  }
```


## Spike and Slab
```{r}
fit_ss <- lm.spike(as.matrix(y_train) ~ as.matrix(X_train), niter = 5000)

y_post_ss <- predict(fit_ss, newdata =as.matrix(rbind(X_train, X_test)))
```


```{r}
qs_ss <- get_qs(t(y_post_ss))


plt_ss <- ggplot(qs_ss) + geom_ribbon(mapping = aes(x = years,
                                              ymin = X2.5.,
                                              ymax = X97.5.),
                                fill = "blue", 
                                alpha = 0.3) +
  geom_line(mapping = aes(x = years, 
                          y = X50.),
            colour = "blue",
            size = 2) +
  geom_line(mapping = aes(x = years, 
                          y = true),
            linetype = 2,
            size = 2) +
  geom_text(mapping = aes(x = 1996, y = 60000, label = "Texas"), size = 6) + 
  geom_text(mapping = aes(x = 1996.5, y = 40000, label = "Synthetic\nTexas"), size = 6) +
  labs(title = "Testing bayesian synthetic control",
       subtitle = "Using Spike and Slab",
       x = "Year",
       y = "Black male prison population") +
  geom_vline(xintercept = 1993, colour = "red", linetype = 3) +
  theme_minimal() + 
  theme(plot.title = element_text(size = 18),
        plot.subtitle = element_text(size = 14),
        plot.background = element_rect(fill = "white"))

plt_ss

ggsave(filename = "Synthetic_Texas_ss.png", plot = plt_ss,
       height = 1500, width = 2000, units = "px")

```